### PR TITLE
[Tracker programs] Add new geometry column (trackedEntityType.featureType)

### PR DESCRIPTION
**Pull request by tokland**
### :pushpin: References

* **Issue:** Closes https://app.clickup.com/t/1vqyygd
* **d2-api**: Requires https://github.com/EyeSeeTea/d2-api/pull/121 -> 1.10.2-beta.2

### :memo: Implementation

- Added new template v3 for tracker programs.
- Added column `geometry` in position C (hidden if no necessary -> featureType = NONE)
- Added entities `Coordinates` and `Geometry`
- Manual parsing of point/polygon (codec should not be used in an entity, no clear repo where to add it; JSON.parse still would need manual type checks).

NOTES:

- An error on the geometry field is an error that stops the process. Do we want instead to skip the cell and continue?
- The type of Polygon in D2 is `Array<Array<[Long, Lat]>>`. That, in fact, allows not one, but multiple polygons. However, the Tracker Capture UI (register & edit profile) only allows creating a single polygon. So, for simplicity, in our domain we have `Array<Long, Lat>` and we only get the first polygon in the API object.  This removes a nesting level which would be confusing for an already complicated column.

### :fire: Notes for the reviewer

3 scenarios to test, depending on `trackedEntityType.featureType`: none, point, polygon. Test rows with and without value. Invalid encoded values should raise a controlled error (snackbar)

### :art: Screenshots

image

### CODE REVIEW

**Comment by tokland** [comment]
- [ ] Check import/export with an TE attribute of type COORDINATE.

**Comment by tokland** [comment]
@SferaDev My bad, uploaded.

**Review by adrianq — APPROVED** [review]
On top of the testing scenarios mentioned by @tokland I also downloaded an excel template generated with an old version of the app, filled it and uploaded using the new version of the application. It works without any problem.

**Comment by SferaDev** [comment]
Great, merging then. @ifoche and I will do final tests before the release

**Pull request merged**
