### PR TITLE
Release 3.16.0

### PR DESCRIPTION
**Pull request by SferaDev**
New in release 3.16.0:

- Propagate tracker data elements from one program stage to others
- Allow different events with the same date on a single file
- Store tracked entity instances asynchronously and avoid HTTP timeouts
- Paginate tracked entity instance requests to solve issues with big servers
- Add metadata version number as additional information
- Scroll multi-selector if the text is bigger than the available UI space

### CODE REVIEW

**Comment by SferaDev** [comment]
> * The "Filter columns for programs" option shows "Program" where it should read "Program Stage":

This was the original behavior but sure I can change it.

> * Up and down arrows to re-order the columns once you add an attribute don't seem to work:

Never has, and this morning re-reading the operational meeting minutes I believe you have "sold" that as a feature. The arrows there are actually a bug, but we never had the ability to re-order the columns from the UI.

> * Not sure if it comes from this code or not, but downloaded a Tracker Program with 1 TEI, where I previously had included one of its attributes to be propagated to the first program stage (the patient id) and the summary say error but the json response seems to be ok with the update

Yes, Estela reported this during the morning.

**Comment by ifoche** [comment]
> > * The "Filter columns for programs" option shows "Program" where it should read "Program Stage":
> This was the original behavior but sure I can change it.
Thanks! I guess that looking at program stages but reading program was just confusing, regardless of when it was introduced in the app
 
> > * Up and down arrows to re-order the columns once you add an attribute don't seem to work:
> Never has, and this morning re-reading the operational meeting minutes I believe you have "sold" that as a feature. The arrows there are actually a bug, but we never had the ability to re-order the columns from the UI.
Ok, I understand now. Well, then at least I guess we should take those arrows out from the interface if they won't work, right? Right now you get a message saying "Settings saved" everytime you click on them, so looks like confusing for the user

> > * Not sure if it comes from this code or not, but downloaded a Tracker Program with 1 TEI, where I previously had included one of its attributes to be propagated to the first program stage (the patient id) and the summary say error but the json response seems to be ok with the update
> 
> Yes, Estela reported this during the morning.
Perfect, thanks!

**Comment by ifoche** [comment]
- Maybe again an error coming from something else but... I created 2 events in preprod for a COVID-19 events program, downloaded the template with them, tried to upload them into training after removing the UIDs of the events, and it fails saying that it cannot find the OU in the system. I had to force the OU in order to get the data imported... which is weird because TRAINING and PREPROD OU trees should be exactly the same but in very rare situations. If you want to check, it's in the Kiandutu health centre that I tested it

**Review by ifoche — APPROVED** [review]
thanks @SferaDev

**Pull request merged**
