### PR TITLE
allow OU tree to show shortName

### PR DESCRIPTION
**Pull request by eperedo**
### :pushpin: References

* **Issue:** Closes https://app.clickup.com/t/860rtu5h4

### :memo: Implementation

- Update [d2-ui-components](https://github.com/EyeSeeTea/d2-ui-components/releases/tag/v2.7.0) to version 2.7.0

### :fire: Notes for the reviewer

Run `yarn install` after pulling changes

### :video_camera: Screenshots/Screen capture

**Download Template - switch OFF**
image

**Download Template - switch ON**
image

**Import Data - switch OFF**
image

**Import Data - switch ON**
image

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@eperedo when you use shortNames I think the alphabetical order is lost, isn't it? How easy would it be to reorder the list after switching to shortNames?

**Comment by eperedo** [comment]
> @eperedo when you use shortNames I think the alphabetical order is lost, isn't it? How easy would it be to reorder the list after switching to shortNames?

Right now is not possible to add the `order` query parameter as a prop.

This requires a change in d2-ui-components https://github.com/EyeSeeTea/d2-ui-components/blob/development/src/org-unit-tree/OrgUnitTree.component.js#L102

Let me know if I should work on this change in d2-ui-components repository.

**Comment by ifoche** [comment]
Ok, then I will just add a new task for this with lower priority (just to be taken in case you don't have other tasks) and will go ahead with this PR without that ordering

**Review by ifoche — APPROVED** [review]
thanks @eperedo

**Pull request merged**
